trigger:
 branches:
   include:
     - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    workingDirectory: frontend
    displayName: 'Install npm dependencies'

  - script: |
      npm run build
    workingDirectory: frontend
    displayName: 'Build application'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'frontend/dist'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish build artifact'
