trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VAR_environment: dev

steps:

# Checkout Code
- checkout: self
  persistCredentials: true

# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

# Terraform Init
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'infra/env/$(TF_VAR_environment)'
    backendServiceArm: 'azure-connection'
    backendAzureRmResourceGroupName: 'tfstate-global-rg'
    backendAzureRmStorageAccountName: 'pankajtfstateprod123'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: '$(TF_VAR_environment)/storage.tfstate'

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'infra/env/$(TF_VAR_environment)'
    environmentServiceNameAzureRM: 'azure-connection'
    varsFile: 'infra/env/$(TF_VAR_environment)/$(TF_VAR_environment).tfvars'
    publishPlanResults: 'true'

# Approval Step
- task: ManualValidation@0
  inputs:
    instructions: 'Review the Terraform Plan. Approve to deploy.'
    onTimeout: 'reject'

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'infra/env/$(TF_VAR_environment)'
    environmentServiceNameAzureRM: 'azure-connection'
    varsFile: 'infra/env/$(TF_VAR_environment)/$(TF_VAR_environment).tfvars'
    allowTelemetryCollection: true
